Repository EunChanNam/We-Share-Wish-Hair, pull requests merged in 2023-04, with the labels that each got.

#136 [Test] User 추가된 service 테스트
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/UserFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/RepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/PointUseRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/PointFindRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: test

#143 [Test] likereview 테스트
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/likereview/LikeReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/likereview/LikeReviewsTest.java
Labels: test

#145 [Test] 리뷰 도메인 테스트
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/RepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewsTest.java
Labels: test, fix

#146 [Refactor, Dev] 일대다관계 삭제 방법 변경
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/dto/response/HairStyleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/domain/Photo.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/domain/PhotoRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/dto/response/PhotoResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/utils/PhotoStore.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewDeleteRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleTest.java
Labels: develop, refactor

#147 [Test, Fix] 리뷰 서비스 테스트
  .gitignore
  src/main/java/com/inq/wishhair/wesharewishhair/photo/domain/PhotoRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/ReviewCreateDto.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/utils/ReviewCreateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewServiceTest.java
Labels: develop, fix

#148 [AND] #10 review write, get
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wishhair/review/ReviewItem.java
  app/src/main/java/com/example/wishhair/review/ReviewPagerAdapter.java
  app/src/main/java/com/example/wishhair/review/detail/ReviewDetailActivity.java
  app/src/main/java/com/example/wishhair/review/my/RecyclerViewAdapterMy.java
  app/src/main/java/com/example/wishhair/review/my/ReviewMyFragment.java
  app/src/main/java/com/example/wishhair/review/recent/RecyclerViewAdapterRecent.java
  app/src/main/java/com/example/wishhair/review/recent/ReviewListFragment.java
  app/src/main/java/com/example/wishhair/review/recent/image receive save
  app/src/main/java/com/example/wishhair/review/write/MyApi.java
  app/src/main/java/com/example/wishhair/review/write/Retrofit2MultipartUploader.java
  app/src/main/java/com/example/wishhair/review/write/WriteReviewActivity.java
  app/src/main/java/com/example/wishhair/sign/LoginActivity.java
  app/src/main/java/com/example/wishhair/sign/UrlConst.java
  app/src/main/res/drawable/border_menu_detail.xml
  app/src/main/res/drawable/write_menu.xml
  app/src/main/res/layout/review_activity_detail.xml
  app/src/main/res/layout/review_fragment_list.xml
  app/src/main/res/layout/review_fragment_my.xml
  app/src/main/res/layout/review_recycler_item_my.xml
  app/src/main/res/layout/review_recycler_item_recent.xml
  app/src/main/res/layout/sign_activity_email_cert.xml
  app/src/main/res/layout/sign_activity_register.xml
  app/src/main/res/menu/menu_review_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  site
Labels: enhancement, develop, refactor, fix

#152 [Test, Fix] 리뷰 정렬 테스트 추가
  .gitignore
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  .gradle/7.6/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.6/dependencies-accessors/gc.properties
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileChanges/last-build.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/com/inq/wishhair/wesharewishhair/auditing/BaseEntity.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/Tag.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/TagType.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewSimpleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointHistory.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/DefaultPageableUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindServiceTest.java
Labels: test, fix

#154 [Refactor] 서비스 구조 리팩토링
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
Labels: refactor

#156 [Refactor] 클래스 기능별로 분리
  src/main/java/com/inq/wishhair/wesharewishhair/auth/service/AuthService.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/UserFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/UserRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/PointSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserRepositoryTest.java
Labels: refactor

#157 [Edit] Photostore 리펙토링
  .gitignore
  src/main/java/com/inq/wishhair/wesharewishhair/photo/dto/response/FileDir.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/dto/response/PhotoResponse.java
  src/test/resources/images/one.png
Labels: edit

#162 [Refactor] 응답 코드 리팩토링
  src/main/java/com/inq/wishhair/wesharewishhair/global/dto/response/PagedResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/dto/response/Paging.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/dto/response/ResponseWrapper.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/dto/response/PagedHairStyleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/dto/response/HairStyleResponseAssembler.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/dto/response/PhotoResponseAssembler.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/response/PagedReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponseAssembler.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/PointSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/response/PagedPointResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/response/SessionIdResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/SessionIdResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/UserResponseAssembler.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/dto/response/PagedWishListResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/dto/response/WishListResponseAssembler.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointSearchServiceTest.java
Labels: refactor

#163 [Test, Refactor]Mypage 서비스 테스트 및 point 서비스 추가테스트
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/PointFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/DefaultPageableUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MyPageServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointSearchServiceTest.java
Labels: refactor, test

#164 [Test, Fix] 추가 controller test
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/utils/PageableUtils.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/PasswordUpdateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/PointUseRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserUpdateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/PointResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/PointControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/PointSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/PasswordUpdateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/PointUseRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MyPageServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: test, fix

#165 [Test, Fix] 유저 추가 api 테스트
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/utils/PageableUtils.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/PasswordUpdateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/PointUseRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserUpdateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/PasswordUpdateDto.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/UserUpdateDto.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/PointResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/PointControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/PointSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/PasswordUpdateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/PointUseRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/UserCreateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/UserUpdateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MyPageServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: test, fix

#167 [Refactor, Test] 리뷰 도매인 리팩토링
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Contents.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewSimpleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/AvailablePoint.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ContentsTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewServiceTest.java
Labels: refactor, test

#168 [Test] Api 테스트에 토큰이 없는 경우 추가 테스트
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/TokenReissueControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/LikeReviewControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
Labels: test

#171 [Feat] 1차 Restdocs 적용
  build.gradle
  src/docs/asciidoc/auth/auth.adoc
  src/docs/asciidoc/auth/token-reissue.adoc
  src/docs/asciidoc/hairstyle/recommend.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/review/like-review.adoc
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/TokenReissueControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/utils/LoginRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/AuthServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/TokenManagerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/TokenReissueServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/config/RestDocsConfig.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/MailDtoFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/PointFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/UserFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepository.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/LikeReviewControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/utils/ReviewCreateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewsTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/PointSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/PasswordUpdateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/UserCreateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/UserUpdateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/PointSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MailSendServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MyPageServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/PointServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: feature

#175 [Feat, Refactor] User validator 구현 기존 코드와 테스트 코드를 리팩토링한다.
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/MailRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/UserRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MailSendService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserValidator.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/MailDto.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/MailDtoFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MailSendServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserValidatorTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/utils/MailDtoUtils.java
Labels: feature, refactor

#177 [Feat, Test] 포인트 충전과 메일 발송을 이벤트로 처리한다.
  src/main/java/com/inq/wishhair/wesharewishhair/review/config/converter/ScoreConverter.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/enums/Score.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/event/PointChargeEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/MailRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/AuthMailSendEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/MailSendEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/RefundMailSendEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/listener/MailSendEventListener.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/listener/PointChargeEventListener.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MailSendService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/MailDto.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewServiceTest.java
Labels: feature, test

#178 [Feat] 리뷰 응답에 아이디 추가
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListSearchController.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
Labels: feature, fix

#180 [Feat, Refactor] 사진 응답을 uri 로 변경하고 테스트 코드를 리팩토링한다.
  .gitignore
  src/main/java/com/inq/wishhair/wesharewishhair/photo/dto/response/PhotoResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
Labels: feature, refactor

#181 [Feat, Refactor] 2차 restdocs 을 적용하고 API 테스트 코드를 리팩토링한다.
  build.gradle
  src/docs/asciidoc/review/like-review.adoc
  src/docs/asciidoc/review/review-search.adoc
  src/docs/asciidoc/review/review.adoc
  src/docs/asciidoc/user/mail.adoc
  src/docs/asciidoc/user/my-page.adoc
  src/docs/asciidoc/user/point-search.adoc
  src/docs/asciidoc/user/point.adoc
  src/docs/asciidoc/user/user.adoc
  src/main/java/com/inq/wishhair/wesharewishhair/auditing/BaseEntity.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/interceptor/AuthInterceptor.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/resolver/PayloadResolver.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/resolver/TokenResolver.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/domain/Token.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/utils/AuthorizationExtractor.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/WishListCount.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/HashTag.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/domain/Photo.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Contents.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReview.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/AuthKeyRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/MailRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/AvailablePoint.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Email.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/FaceShape.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Nickname.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Password.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointHistory.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishList.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/dto/response/WishListResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/RepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/PointFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MailControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/PointControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/PointSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
Labels: feature, refactor

#185 [Feat] 네이버 클라우드 스토리지를 연동해서 이미지를 업로드하도록 변경한다
  .gitignore
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/photo/config/S3ObjectStorageConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/domain/Photo.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/dto/response/PhotoResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/utils/PhotoStore.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MailSendServiceTest.java
Labels: feature

#194 [Feat, Refactor] 리뷰 단건 조회 구현 후 리뷰 응답에 iswriter 추가한다. 추가로 findWithLikeReviewsById 로직 위치를 바꿔 리팩토링 한다.
  src/docs/asciidoc/review/review-search.adoc
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponseAssembler.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageControllerTest.java
Labels: feature, refactor

#195 [Feat] 리뷰 좋아요 동시성 제어(비관적 락)를 적용한다
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageControllerTest.java
Labels: feature

#196 [Feat] 사용자 정보 조회 api 구현하고 테스트 후 명세한다.
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user/user-info.adoc
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserInfoController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserInfoService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/UserInformation.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/UserResponseAssembler.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserInfoControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserInfoServiceTest.java
Labels: feature

#197 [Feat] 비밀번호 크립토 암호화 적용
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/auth/service/AuthService.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/config/SecurityConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/SignUpRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Password.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/AuthServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/UserFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/PasswordUpdateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/SignUpRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/PasswordTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: feature

#198 [Test, Feat] wishlist 를 테스트하고 wishlist 응답을 수정한다.
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/wishlist/wish-list-search.adoc
  src/docs/asciidoc/wishlist/wish-list.adoc
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishList.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/dto/response/WishListResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/RepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListServiceTest.java
Labels: feature, test

#201 [Refactor] 리뷰 - Query dsl 을 적용해서 좋아요 구조를 리팩토링하고 동시성 제어를 리팩토링한다.
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/global/config/QueryDslConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/common/ReviewSortCondition.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepositoryImpl.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishList.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListSearchRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/RepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/config/QueryDslConfig.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListSearchRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListServiceTest.java
Labels: refactor

#204 [Refactor] 메일 로직을 리팩토링하고 템플릿을 적용한다
  build.gradle
  src/docs/asciidoc/auth/mail.adoc
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/MailAuthController.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/event/AuthMailSendEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/config/MailAsyncConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/mail/dto/RefundMailDto.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/mail/event/MailSendEventListener.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/mail/utils/EmailSender.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/PointUseRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/event/PointChargeEventListener.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/AuthMailSendEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/MailSendEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/RefundMailSendEvent.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/event/listener/MailSendEventListener.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MailSendService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/MailDto.java
  src/main/resources/templates/AuthMailTemplate.html
  src/main/resources/templates/RefundRequestMailTemplate.html
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/MailAuthControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MailSendServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/utils/MailDtoUtils.java
Labels: refactor

#207 [Refactor] 리뷰 조회 쿼리를 리팩토링한다.
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepositoryImpl.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/infra/query/dto/response/ReviewQueryResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewDetailResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponseAssembler.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserInfoControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListSearchRepositoryTest.java
Labels: refactor

#212 [Refactor] photo 저장 후 응답값 변경하고 service 를 구현하여 리팩토링한다
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/domain/Photo.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/service/PhotoService.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/utils/PhotoStore.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/ReviewFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/infra/query/HairStyleQueryRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/controller/utils/ReviewCreateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/review/service/ReviewServiceTest.java
Labels: refactor

#220 [refactor] 헤어스타일 조회 쿼리를 리팩토링 하고 바뀐 wishHair API 를 테스트한다.
  src/docs/asciidoc/hairstyle/hair-search.adoc
  src/docs/asciidoc/hairstyle/wish-hair.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/inq/wishhair/wesharewishhair/global/utils/PageableUtils.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/WishHairController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/WishListCount.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/infra/query/HairStyleQueryRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/infra/query/HairStyleQueryRepositoryImpl.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchService.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/utils/HairRecommendCondition.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewSearchController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/infra/query/ReviewQueryRepositoryImpl.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/utils/ReviewSortCondition.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/DefaultPageableUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleSearchControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/WishHairControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/infra/query/HairStyleQueryRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleSearchServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/utils/HairRecommendConditionUtils.java
Labels: refactor
