Repository EunChanNam/We-Share-Wish-Hair, pull requests merged in 2023-03, with the labels that each got.

#17 기능 추가 및 수정
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/inq/wishhair/wesharewishhair/domain/hairstyle/repository/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/hairstyle/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/hairstyle/dto/response/PagedHairStyleResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/common/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/common/utils/UserSessionDtoUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/login/controller/LoginControllerTest.java
Labels: edit, test

#18 [로그인 방식 수정] Token-domain 작성
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/Token.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/repository/TokenRepository.java
Labels: feature

#20 [로그인 방식 수정] Token Utils 작성
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/utils/JwtTokenProvider.java
  src/main/java/com/inq/wishhair/wesharewishhair/exception/ErrorCode.java
Labels: feature

#21 [로그인 방식 수정] Token Servic 구현
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/Token.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/repository/TokenRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/AuthService.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/TokenManager.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/TokenReissueService.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/dto/response/TokenResponse.java
Labels: feature

#22 [로그인 방식 수정] 로그인에 RTR 방식 적용
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/repository/TokenRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/TokenManager.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/TokenReissueService.java
Labels: feature, edit

#26 [로그인 방식 수정] TokenResolver, PayloadResolver 구현
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/AuthConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/ExtractPayload.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/ExtractToken.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/PayloadResolver.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/TokenResolver.java
Labels: feature

#27 [로그인 방식 수정] Auth Interceptor 구현
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/AuthConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/interceptor/AuthInterceptor.java
Labels: feature

#28 [로그인 방식 수정] Session 로직 제거
  src/main/java/com/inq/wishhair/wesharewishhair/domain/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/hairstyle/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/review/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/user/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/user/dto/response/MyPageResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/wishlist/WishListController.java
  src/test/java/com/inq/wishhair/wesharewishhair/common/utils/UserSessionDtoUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
Labels: edit

#35 [BE] 로그인 : Session -> Jwt Token 방식으로 교체
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/Token.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/AuthConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/interceptor/AuthInterceptor.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/ExtractPayload.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/ExtractToken.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/PayloadResolver.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/config/resolver/TokenResolver.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/repository/TokenRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/AuthService.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/TokenManager.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/TokenReissueService.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/service/dto/response/TokenResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/utils/AuthorizationExtractor.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/auth/utils/JwtTokenProvider.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/login/LoginService.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/login/dto/UserSessionDto.java
  src/main/java/com/inq/wishhair/wesharewishhair/domain/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/auth/AuthController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/auth/TokenReissueController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/auth/dto/request/LoginRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/hairstyle/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/login/LoginController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/login/dto/LoginRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/review/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/user/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/user/dto/response/MyPageResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/web/wishlist/WishListController.java
  src/test/java/com/inq/wishhair/wesharewishhair/common/utils/UserSessionDtoUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/login/controller/LoginControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/login/controller/utils/LoginRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/login/service/LoginServiceTest.java
Labels: feature, edit

#36 [패지지 구조 변경] Point -> User 통합
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/response/MyPageResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/domain/PointHistory.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/domain/PointRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/enums/PointType.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserPointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepository.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: refactor

#37 [패키지 구조 변경] HashTag -> HairStyle 통합
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/HashTag.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/Tag.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleTest.java
Labels: refactor

#40 [패키지 구조 변경] LikeReview -> Review 통합
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/domain/LikeReview.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/domain/LikeReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
Labels: refactor

#42 [응답 구조 변경] HairStyle 응답구조 변경
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/dto/response/HairStyleResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
Labels: refactor

#43 [응답 구조 변경] Review 응답구조 변경
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/LikeReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/response/PagedReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReview.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
Labels: refactor, edit

#44 [응답 구조 변경] My-Page 로직 및 응답 분리
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointHistory.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointType.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserPointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/MyPageResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepository.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: refactor

#45 [구조 변경] User 기능별 service 분리
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
Labels: refactor

#46 [구조 리펙토링] wish-list 응답, 로직 구조 변경 + 모든 응답 제네릭 제거
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/dto/response/PagedHairStyleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/response/PagedReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/dto/response/PagedWishListResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/dto/response/WishListResponse.java
Labels: refactor, edit

#47 [BE] 응답 및 로직 구조 리펙토링
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/dto/response/PagedHairStyleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/dto/response/HairStyleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/LikeReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/response/PagedReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReview.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointHistory.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointType.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserPointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/MyPageResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/dto/response/PagedWishListResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/dto/response/WishListResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepository.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: refactor, edit

#48 [Auth Test] 도메인 테스트
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepository.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
Labels: test, fix

#49 [Auth Test] JwtTokenProvider test
  .gitignore
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/gradle.xml
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/auth/utils/JwtTokenProvider.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/utils/JwtTokenProviderTest.java
  src/test/resources/application-test.yml
Labels: test, fix

#50 [AND] #5 review write UI
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wishhair/review/WriteReviewActivity.java
  app/src/main/java/com/example/wishhair/review/WriteReviewAdapter.java
  app/src/main/java/com/example/wishhair/review/write/WriteReviewActivity.java
  app/src/main/java/com/example/wishhair/review/write/WriteReviewAdapter.java
  app/src/main/java/com/example/wishhair/sign/LoginActivity.java
  app/src/main/java/com/example/wishhair/sign/RegisterActivity.java
  app/src/main/res/layout/review_activity_write.xml
  app/src/main/res/layout/review_item_write_picture.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  site
Labels: feature, edit

#52 [Auth Test] auth - service test
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/AuthConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/service/TokenReissueService.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/AuthServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/TokenManagerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/TokenReissueServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
Labels: test, fix

#53 [Auth Test] controller test
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/AuthConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/interceptor/AuthInterceptor.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthController.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/utils/JwtTokenProvider.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/TokenReissueControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/utils/LoginRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/utils/JwtTokenProviderTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/TokenUtils.java
Labels: bug, fix

#54 [BE] Auth 테스트
  .gitignore
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/gradle.xml
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/AuthConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/interceptor/AuthInterceptor.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthController.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/service/TokenReissueService.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/utils/JwtTokenProvider.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/TokenReissueControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/utils/LoginRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/domain/TokenRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/AuthServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/TokenManagerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/TokenReissueServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/utils/JwtTokenProviderTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/TokenUtils.java
  src/test/resources/application-test.yml
Labels: test, fix

#55 [HairStyle Test] domain 테스트
  src/main/java/com/inq/wishhair/wesharewishhair/photo/entity/Photo.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepositoryTest.java
Labels: test

#57 [Hair-Style Test] controller 테스트
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/Tag.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
Labels: edit, test

#58 [BE] Hair_Style 테스트
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/Tag.java
  src/main/java/com/inq/wishhair/wesharewishhair/photo/entity/Photo.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/PageableUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
Labels: edit, test, fix

#60 [AND] #6 feature logic
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wishhair/MyPage/MyPageFragment.java
  app/src/main/java/com/example/wishhair/sign/LoginActivity.java
  app/src/main/java/com/example/wishhair/sign/LoginRequest.java
  app/src/main/java/com/example/wishhair/sign/RegisterActivity.java
  app/src/main/java/com/example/wishhair/sign/UrlConst.java
  app/src/main/res/drawable/sign_email.png
  app/src/main/res/drawable/sign_name.png
  app/src/main/res/drawable/sign_star_black.png
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/sign_activity_login.xml
  app/src/main/res/layout/sign_activity_register.xml
  site
Labels: feature

#61 [리뷰 스펙 수정] title 속성 제거
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/ReviewCreateDto.java
Labels: edit

#62 [리뷰 스펙 추가] Review - 좋아요 수 스펙 추가
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
Labels: feature, edit

#63 [BE] 리뷰 스펙 추가 및 수정
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/ReviewCreateDto.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
Labels: feature, edit

#65 [BE] 리뷰 코드 리펙토링
  src/main/java/com/inq/wishhair/wesharewishhair/global/consts/Condition.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/common/ReviewSortCondition.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/response/PagedReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReview.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
Labels: refactor

#75 [AND] #7 homeFragment
  app/src/main/java/com/example/wishhair/HomeFragment.java
  app/src/main/java/com/example/wishhair/HomeHotReviewAdapter.java
  app/src/main/java/com/example/wishhair/HomeItems.java
  app/src/main/java/com/example/wishhair/HomeRecommendAdapter.java
  app/src/main/java/com/example/wishhair/review/RecyclerViewAdapterHot.java
  app/src/main/java/com/example/wishhair/review/detail/ReviewDetailActivity.java
  app/src/main/java/com/example/wishhair/review/write/WriteReviewAdapter.java
  app/src/main/java/com/example/wishhair/sign/LoginActivity.java
  app/src/main/res/drawable/home_bell.xml
  app/src/main/res/drawable/home_shape_circle_button.xml
  app/src/main/res/drawable/shape_indicator_select.xml
  app/src/main/res/drawable/shape_indicator_un_select.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_item_reco_style.xml
  app/src/main/res/layout/home_item_review_hot.xml
  app/src/main/res/values/strings.xml
Labels: feature, edit

#76 [BE] LikeReview 구조 변경
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReview.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
Labels: edit

#77 [BE] 리뷰 응답 스펙에 해시태그 추가
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/HashTag.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/dto/response/HairStyleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/dto/response/HashTagResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
Labels: feature, edit

#78 [BE] User 스펙 수정
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthController.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/service/AuthService.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/Tag.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/TagType.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Email.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/FaceShape.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/UserRepository.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/AuthServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/UserFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/UserCreateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserTest.java
Labels: feature, edit

#80 [BE] 이메일 인증 구현
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/AuthKeyRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/MailRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Email.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MailSendService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/MailDto.java
Labels: feature

#84 AND_refactor
  app/src/main/java/com/example/wishhair/MainActivity.java
  app/src/main/java/com/example/wishhair/MyPage/CouponList.java
  app/src/main/java/com/example/wishhair/MyPage/CouponReceive.java
  app/src/main/java/com/example/wishhair/MyPage/MyCouponFragment.java
  app/src/main/java/com/example/wishhair/MyPage/MyHeartlistFragment.java
  app/src/main/java/com/example/wishhair/MyPage/MyInformationFragment.java
  app/src/main/java/com/example/wishhair/MyPage/MyPageFragment.java
  app/src/main/java/com/example/wishhair/MyPage/MyPointList.java
  app/src/main/java/com/example/wishhair/MyPage/MyStyleFragment.java
  app/src/main/java/com/example/wishhair/home/HomeFragment.java
  app/src/main/java/com/example/wishhair/home/HomeHotReviewAdapter.java
  app/src/main/java/com/example/wishhair/home/HomeItems.java
  app/src/main/java/com/example/wishhair/home/HomeRecommendAdapter.java
  app/src/main/res/layout/coupon_list_fragment.xml
  app/src/main/res/layout/coupon_recieve_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/my_coupon_fragment.xml
  app/src/main/res/layout/my_information_fragment.xml
  app/src/main/res/layout/my_point_list_fragment.xml
  app/src/main/res/layout/my_selectionlist_fragment.xml
  app/src/main/res/layout/my_style_fragment.xml
  app/src/main/res/layout/mypage_fragment.xml
Labels: refactor

#86 [BE] User, 이메일 검증 테스트
  src/main/java/com/inq/wishhair/wesharewishhair/auth/config/AuthConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/MailRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Email.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MailSendService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/MailDto.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/MailDtoFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/TokenUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MailControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/EmailTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/FaceShapeTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MailSendServiceTest.java
Labels: edit, test, fix

#88 [BE] ModelAttribute -> RequestBody
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthController.java
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/AuthKeyRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/MailRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserCreateRequest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/TokenReissueControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/utils/TokenUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MailControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
Labels: edit

#89 Pagable 정렬 버그 픽스
  src/main/java/com/inq/wishhair/wesharewishhair/review/common/ReviewSortCondition.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MyPageController.java
Labels: edit

#90 [Point 기능 개발] Point 구조 리팩토링
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/AvailablePoint.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointHistory.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointType.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/MyPageResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: refactor, edit

#92 [BE] Point 기능 개발
  src/main/java/com/inq/wishhair/wesharewishhair/global/dto/response/Paging.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/Review.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/likereview/LikeReviews.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/PointFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/response/PagedPointResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/AvailablePoint.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointHistory.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/point/PointType.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserPointService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/MyPageResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/PointResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/testrepository/PointHistoryTestRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/UserServiceTest.java
Labels: feature, refactor, edit

#93 [BE] Paging 응답 적용
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/response/PagedReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/dto/response/PagedWishListResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/dto/response/WishListResponse.java
Labels: edit

#95 [BE] No-Content -> Success 로 변경
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthController.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/dto/response/Success.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/LikeReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MailControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/UserControllerTest.java
Labels: edit

#96 [BE] 나의 리뷰 조회 구현
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/LikeReviewController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/LikeReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MyPageService.java
Labels: feature, refactor

#98 [BE] Session 연동코드 추가
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/response/SessionIdResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/MailControllerTest.java
Labels: feature

#101 [BE] likes 정렬 버그 픽스
  src/main/java/com/inq/wishhair/wesharewishhair/review/common/ReviewSortCondition.java
Labels: fix

#102 [BE] paing 응답 스펙 버그 픽스
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/response/PagedReviewResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/response/PagedPointResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/dto/response/PagedWishListResponse.java
Labels: fix

#104 [BE] 헤어스타일 찜개수 속성 추가
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/WishListCount.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/controller/WishListController.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishList.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/domain/WishListRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/wishlist/service/WishListService.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/controller/AuthControllerTest.java
Labels: develop

#105 [AND] #8 3월 4주 작업
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wishhair/CustomRetryPolicy.java
  app/src/main/java/com/example/wishhair/CustomTokenHandler.java
  app/src/main/java/com/example/wishhair/MyPage/MyPageFragment.java
  app/src/main/java/com/example/wishhair/home/HomeFragment.java
  app/src/main/java/com/example/wishhair/review/ReviewFragment.java
  app/src/main/java/com/example/wishhair/review/recent/ReviewListFragment.java
  app/src/main/java/com/example/wishhair/review/write/WriteRequestData.java
  app/src/main/java/com/example/wishhair/review/write/WriteReviewActivity.java
  app/src/main/java/com/example/wishhair/sign/EmailCertActivity.java
  app/src/main/java/com/example/wishhair/sign/LoginActivity.java
  app/src/main/java/com/example/wishhair/sign/LoginRequest.java
  app/src/main/java/com/example/wishhair/sign/RegisterActivity.java
  app/src/main/java/com/example/wishhair/sign/RegisterRequest.java
  app/src/main/java/com/example/wishhair/sign/UrlConst.java
  app/src/main/java/com/example/wishhair/sign/loginStringRequest Backup
  app/src/main/res/drawable/sign_email.png
  app/src/main/res/drawable/sign_email.xml
  app/src/main/res/drawable/sign_name.png
  app/src/main/res/drawable/sign_name.xml
  app/src/main/res/drawable/sign_pw.png
  app/src/main/res/drawable/sign_pw.xml
  app/src/main/res/drawable/sign_star.xml
  app/src/main/res/drawable/sign_star_black.png
  app/src/main/res/layout/review_fragment.xml
  app/src/main/res/layout/review_fragment_list.xml
  app/src/main/res/layout/sign_activity_email_cert.xml
  app/src/main/res/layout/sign_activity_login.xml
  app/src/main/res/layout/sign_activity_register.xml
  app/src/main/res/values/strings.xml
Labels: develop, refactor, edit

#107 [BE] 헤어추천 조건 추가
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyle.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/hashtag/enums/Tag.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/HairStyleFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
Labels: develop, test, fix

#108 [BE] 사용자 얼굴형 기반 맞춤 헤어 추천 개발
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/dto/response/PagedHairStyleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/test/java/com/inq/wishhair/wesharewishhair/global/base/ServiceTest.java
Labels: develop

#110 [AND] #9 review write
  app/build.gradle
  app/src/main/java/com/example/wishhair/review/ReviewPagerAdapter.java
  app/src/main/java/com/example/wishhair/review/recent/ReviewListFragment.java
  app/src/main/java/com/example/wishhair/review/recent/my/RecyclerViewAdapterMy.java
  app/src/main/java/com/example/wishhair/review/recent/my/ReviewMyFragment.java
  app/src/main/java/com/example/wishhair/review/write/MyApi.java
  app/src/main/java/com/example/wishhair/review/write/Retrofit2MultipartUploader.java
  app/src/main/java/com/example/wishhair/review/write/WriteRequestData.java
  app/src/main/java/com/example/wishhair/review/write/WriteReviewActivity.java
  app/src/main/java/com/example/wishhair/review/write/WriteReviewAdapter.java
  app/src/main/java/com/example/wishhair/sign/UrlConst.java
  app/src/main/res/layout/review_fragment_my.xml
  site
Labels: develop, edit, fix

#112 [BE] 이달의 추천 리뷰 api 구현
  src/main/java/com/inq/wishhair/wesharewishhair/global/dto/response/SimpleResponseWrapper.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/ReviewFindController.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewSimpleResponse.java
Labels: develop

#113 [BE] 홈화면 헤어추천 api test
  src/main/java/com/inq/wishhair/wesharewishhair/global/consts/SessionConst.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/utils/PageableUtils.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleController.java
  src/main/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/controller/HairStyleControllerTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/domain/HairStyleRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/hairstyle/service/HairStyleServiceTest.java
Labels: refactor, test

#117 [BE] 리뷰 조회 버그 픽스
  src/main/java/com/inq/wishhair/wesharewishhair/review/domain/ReviewFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewFindService.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
Labels: refactor, fix

#122 [BE] Golbal error 처리하기
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ApiExceptionHandler.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
Labels: develop

#123 [BE] 요청에 검증 어노테이션 추가
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/com/inq/wishhair/wesharewishhair/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/controller/dto/request/ReviewRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/AuthKeyRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/MailRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserCreateRequest.java
Labels: develop

#124 [BE] 리뷰 응답스펙 수정 및 score 컨버터 구현
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/config/ReviewConfig.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/config/converter/ScoreConverter.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewResponse.java
Labels: develop, edit

#128 [BE] 유저 도메인 수정
  src/main/java/com/inq/wishhair/wesharewishhair/auth/service/AuthService.java
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/dto/response/ReviewSimpleResponse.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Nickname.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Password.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/response/MyPageResponse.java
  src/test/java/com/inq/wishhair/wesharewishhair/auth/service/AuthServiceTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/fixture/UserFixture.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/controller/utils/UserCreateRequestUtils.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserRepositoryTest.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/domain/UserTest.java
Labels: develop, edit

#131 [BE] 유저 정보 수정 구현
  src/main/java/com/inq/wishhair/wesharewishhair/global/exception/ErrorCode.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/UserController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/PasswordUpdateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/UserUpdateRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Nickname.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/Password.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/User.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/domain/UserFindRepository.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/UserService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/PasswordUpdateDto.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/dto/UserUpdateDto.java
Labels: develop

#134 [BE] 포인트 사용 구현
  src/main/java/com/inq/wishhair/wesharewishhair/review/service/ReviewService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/MailController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/PointController.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/controller/dto/request/PointUseRequest.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/MailSendService.java
  src/main/java/com/inq/wishhair/wesharewishhair/user/service/PointService.java
  src/test/java/com/inq/wishhair/wesharewishhair/user/service/MailSendServiceTest.java
Labels: develop
